site_name: PiCommander
nav:
  - Home: index.md
  - Usage: usage.md
theme:
  name: readthedocs
  highlightjs: true
  prev_next_buttons_location: both
  shortcuts:
      help: 191    # ?
      next: 78     # n
      previous: 80 # p
      search: 83   # s

plugins:
  - search
